# Generated by Django 4.2.5 on 2023-09-10 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TaskApp', '0002_alter_tasks_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks_set', to='TaskApp.project'),
        ),
    ]
